run_name: 'run-1'
experiment_name: 'v0.1'
comet_project_name: 'space-3d'
cuda: True
gpu_id: '0'
num_workers: 4

train:
  data_dir: '/mnt/ialabnas/datasets/CLEVR_v1.0/images/train'
  batch_size: 4
  epochs: 20
  snapshot_interval: 5
  it_log_interval: 1000
  generator:
    optimizer:
      lr: 0.0005
      betas: [0.5, 0.999]
  scene_encoder:
    optimizer:
      lr: 0.0005
      betas: [0.5, 0.999]
    kl_weight: 0.000001

model:
  generator:
    z_dim_bg: 64
    z_dim_fg: 128
    w_dim_bg: 256
    w_dim_fg: 512
    filters: [64, 64]
    ks: [4, 4]
    strides: [2, 2]
    use_learnable_proj: False
    use_inverse_transform: False
