run_name: 'run1'
experiment_name: 'object_t'
comet_project_name: 'train-gan'

train:
  data_dir: '/mnt/ialabnas/datasets/CLEVR_v1.0/images/train'
  batch_size: 64
  epochs: 50
  snapshot_interval: 5
  image_height: 64
  image_width: 64
  it_log_interval: 500
  generator:
    optimizer:
      learning_rate: 0.0001
      beta_1: 0.5
      beta_2: 0.999
    update_freq: 2
    fixed_z: False
  discriminator:
    optimizer:
      learning_rate: 0.0001
      beta_1: 0.5
      beta_2: 0.999
    random_noise: False

model:
  generator:
    z_dim_bg: 64
    z_dim_fg: 128
    w_dim_bg: 256
    w_dim_fg: 512
    filters: [64, 64, 64]
    ks: [1, 4, 4]
    strides: [1, 2, 2]
    use_learnable_proj: False
  discriminator:
    filters: [64, 128, 256, 512]
    ks: [5, 5, 5, 5]
    strides: [2, 2, 2, 2]