run_name: 'style&proj&curriculum-run1'
experiment_name: 'torch-fix'
comet_project_name: 'torch-fix'
cuda: True
gpu_id: '0'
num_workers: 4

train:
  data_dir: '/mnt/ialabnas/datasets/CLEVR_v1.0/images/train'
  batch_size: 64
  epochs: 150
  snapshot_interval: 5
  image_height: 64
  image_width: 64
  it_log_interval: 200
  obj_num_increase_epoch: 1
  generator:
    optimizer:
      lr: 0.0001
      betas: [0.5, 0.999]
    update_freq: 2
    fixed_z: False
  discriminator:
    optimizer:
      lr: 0.0001
      betas: [0.5, 0.999]
    random_noise: False

model:
  generator:
    z_dim_bg: 64
    z_dim_fg: 128
    w_dim_bg: 256
    w_dim_fg: 512
    filters: [64, 64]
    ks: [4, 4]
    strides: [2, 2]
    use_learnable_proj: False
  discriminator:
    style_discriminator: True
    filters: [64, 128, 256, 512]
    ks: [5, 5, 5, 5]
    strides: [2, 2, 2, 2]